"""Shared test-tier manifest for dev tooling and pytest collection."""

from __future__ import annotations

from pathlib import Path


FAST_TEST_FILES = (
    "test_background_peak_matching.py",
    "test_background_theta_helpers.py",
    "test_cli_cif_parse.py",
    "test_cli_geometry_fit.py",
    "test_compare_intensity.py",
    "test_config_loader.py",
    "test_data_loading_parameters.py",
    "test_debug_controls.py",
    "test_debug_utils.py",
    "test_dependency_metadata.py",
    "test_dev_cli.py",
    "test_dev_doctor.py",
    "test_diagnostics_classification.py",
    "test_hbn_path_resolution.py",
    "test_import_smoke.py",
    "test_repo_debt_report.py",
    "test_structure_factor_atomic_coordinates.py",
    "test_test_tiers_complete.py",
)
INTEGRATION_TEST_FILES = (
    "test_cli_headless.py",
    "test_geometry_fit_landscape.py",
    "test_geometry_fit_quality_baseline.py",
    "test_geometry_fitting.py",
    "test_gui_geometry_fit_workflow.py",
    "test_hbn_fitter_bundle_export.py",
    "test_simulation.py",
    "test_simulation_engine.py",
)
SLOW_TEST_FILES = (
    "test_atomic_scattering_factors.py",
    "test_beam_center_pick_helpers.py",
    "test_bi2se3_structure_factor.py",
    "test_diffraction_constraints.py",
    "test_diffraction_inner_loop_optimizations.py",
    "test_diffraction_local_arc.py",
    "test_diffraction_safe_wrapper.py",
    "test_diffraction_subpixel.py",
    "test_diffraction_tools_module.py",
    "test_diffraction_tools_view.py",
    "test_diffraction_weighted_events.py",
    "test_disordered_phase_current_refresh.py",
    "test_disordered_phase_end_to_end.py",
    "test_disordered_phase_hit_table_scheduling.py",
    "test_disordered_phase_hit_tables.py",
    "test_disordered_phase_invalidation.py",
    "test_disordered_phase_inventory.py",
    "test_disordered_phase_inventory_live_path.py",
    "test_disordered_phase_live_q_group_refresh.py",
    "test_disordered_phase_live_runtime_regression.py",
    "test_disordered_phase_logging.py",
    "test_disordered_phase_picker_to_fitter_end_to_end.py",
    "test_disordered_phase_q_group_cache.py",
    "test_disordered_phase_real_inventory.py",
    "test_disordered_phase_source_labels.py",
    "test_disordered_phase_state.py",
    "test_disordered_phase_state_io.py",
    "test_disordered_phase_ui_enable.py",
    "test_disordered_phase_user_report_live_path.py",
    "test_exact_cake_portable.py",
    "test_exact_qspace_portable.py",
    "test_fit_cache_controls.py",
    "test_fresnel_calls.py",
    "test_geometry_fit_correlation.py",
    "test_geometry_fit_disordered_phase.py",
    "test_geometry_fit_disordered_preflight.py",
    "test_geometry_fit_fresh_rebuild_consumer.py",
    "test_geometry_fit_job_live_rows_handoff.py",
    "test_geometry_fit_lattice_ui_helpers.py",
    "test_geometry_fit_live_cache_validation_acceptance.py",
    "test_geometry_fit_live_rows_signature_handoff.py",
    "test_geometry_fit_manual_fit_space_classification.py",
    "test_geometry_fit_safe_runtime.py",
    "test_geometry_fit_source_cache_rungs.py",
    "test_geometry_line_orientation.py",
    "test_geometry_objective_cache.py",
    "test_geometry_overlay.py",
    "test_gui_analysis_figure_controls.py",
    "test_gui_analysis_peak_tools.py",
    "test_gui_analysis_quick_controls.py",
    "test_gui_analysis_visibility.py",
    "test_gui_app_helpers.py",
    "test_gui_app_import_safe.py",
    "test_gui_background.py",
    "test_gui_background_manager.py",
    "test_gui_bootstrap.py",
    "test_gui_bragg_qr_manager.py",
    "test_gui_canvas_interactions.py",
    "test_gui_controllers.py",
    "test_gui_diffuse_cif_toggle.py",
    "test_gui_display_projection.py",
    "test_gui_fast_plot_viewer.py",
    "test_gui_fit2d_error_sound.py",
    "test_gui_geometry_q_group_manager.py",
    "test_gui_integration_range_drag.py",
    "test_gui_lazy_runtime.py",
    "test_gui_main_figure_chrome.py",
    "test_gui_main_matplotlib_interaction.py",
    "test_gui_ordered_structure_fit.py",
    "test_gui_overlays.py",
    "test_gui_peak_selection.py",
    "test_gui_qr_cylinder_overlay.py",
    "test_gui_runtime_background.py",
    "test_gui_runtime_detector_remap_cache.py",
    "test_gui_runtime_display_acceleration.py",
    "test_gui_runtime_fit_analysis.py",
    "test_gui_runtime_geometry_fit.py",
    "test_gui_runtime_geometry_fitter_cache_handoff.py",
    "test_gui_runtime_geometry_fitter_handoff_fast.py",
    "test_gui_runtime_geometry_interaction.py",
    "test_gui_runtime_geometry_preview.py",
    "test_gui_runtime_import_safe.py",
    "test_gui_runtime_invalidation.py",
    "test_gui_runtime_mixed_update_regressions.py",
    "test_gui_runtime_optimization_scenarios.py",
    "test_gui_runtime_position_preview.py",
    "test_gui_runtime_primary_cache.py",
    "test_gui_runtime_primary_viewport.py",
    "test_gui_runtime_qr_cylinder_overlay.py",
    "test_gui_runtime_update_actions.py",
    "test_gui_runtime_update_dependencies.py",
    "test_gui_runtime_update_trace.py",
    "test_gui_sim_signature.py",
    "test_gui_sliders.py",
    "test_gui_state_io.py",
    "test_gui_state_restore_helpers.py",
    "test_gui_structure_factor_pruning.py",
    "test_gui_structure_model.py",
    "test_gui_tk_primary_viewport.py",
    "test_gui_views.py",
    "test_gui_window_affinity.py",
    "test_hbn_geometry_import_safe.py",
    "test_hbn_geometry_mapping.py",
    "test_ht_analytical.py",
    "test_install_prereqs.py",
    "test_intensities.py",
    "test_intersection_analysis.py",
    "test_intersection_cache_schema.py",
    "test_launcher_routing.py",
    "test_logging_controls.py",
    "test_main_entrypoint_import_safe.py",
    "test_main_geometry_fit_helpers.py",
    "test_manual_detector_to_caked_refresh.py",
    "test_manual_geometry_disordered_state_io.py",
    "test_manual_geometry_live_peak_cache.py",
    "test_manual_geometry_selection_helpers.py",
    "test_manual_picker_disordered_detector_positions.py",
    "test_manual_picker_disordered_phase.py",
    "test_manual_placement_disordered_source.py",
    "test_mosaic_intensity_conservation.py",
    "test_mosaic_profiles_rng.py",
    "test_mosaic_shape_optimization.py",
    "test_mosaic_width_optimization.py",
    "test_numba_cache_env.py",
    "test_numba_compat.py",
    "test_osc_reader.py",
    "test_parallel_utils.py",
    "test_pbi2_ht_shift_cif.py",
    "test_peak_multiplicity_cache.py",
    "test_peak_sensitivity.py",
    "test_peak_transport_validation.py",
    "test_plot_excel_scatter.py",
    "test_projection_alignment_contract.py",
    "test_q_group_duplicate_source_identity.py",
    "test_q_space_viewer_runtime.py",
    "test_qr_cylinder_overlay.py",
    "test_qr_grouping.py",
    "test_raw_structure_factor_api.py",
    "test_rod_profiles.py",
    "test_runtime_qr_selector_cache_policy.py",
    "test_sitecustomize.py",
    "test_source_template_cache.py",
    "test_stacking_fault_cache_invalidation.py",
    "test_stacking_fault_diffuse_f2_q.py",
    "test_stacking_fault_redundancy.py",
    "test_structure_factor_environment.py",
    "test_structure_factor_sites.py",
    "test_structure_factor_switch_sweep.py",
    "test_user_paths.py",
    "test_utils_notifications.py",
    "test_vesta_reference_parser.py",
)
DIAGNOSTIC_TEST_FILES = (
    "test_background_peak_fits_notebook.py",
    "test_bi2se3_residual_diagnostics.py",
    "test_bi2se3_validation_doc_consistency.py",
    "test_bi2se3_vesta_geometry.py",
    "test_bi2se3_vesta_reference_regression.py",
    "test_compare_bi2se3_reference_tool.py",
    "test_compare_single_hkl_debug_script.py",
    "test_fast_manual_point_runtime_profiles.py",
    "test_geometry_fit_live_cache_diagnostics.py",
    "test_geometry_fitter_cache_regression_gate_script.py",
    "test_manual_picker_source_diagnostics.py",
    "test_new4_rung2_contract.py",
    "test_single_hkl_debug_payload.py",
    "test_testing_validation_index.py",
    "test_timing.py",
)
BENCHMARK_TEST_FILES = ()
BENCHMARK_TEST_DIR = "tests/benchmarks"


def fast_test_paths(root: Path) -> list[str]:
    return [str(root / "tests" / name) for name in FAST_TEST_FILES]


def integration_test_paths(root: Path) -> list[str]:
    return [str(root / "tests" / name) for name in INTEGRATION_TEST_FILES]
